// The startup sweep trashes Steam's ~/Applications shortcut once its game is uninstalled.
// Each case builds a throwaway HOME and checks which shortcuts are left.
#include "../feats/shortcuts.c"

#include <errno.h>
#include <unistd.h>

static int failures;
static char home[PATH_MAX];

static void write_at(const char *rel, const char *content) {
    char path[PATH_MAX];
    snprintf(path, sizeof(path), "%s/%s", home, rel);
    for (char *p = path + strlen(home) + 1; *p; p++) {
        if (*p != '/') continue;
        *p = '\0';
        mkdir(path, 0755);
        *p = '/';
    }
    if (!content) {
        mkdir(path, 0755);
        return;
    }
    FILE *f = fopen(path, "w");
    fputs(content, f);
    fclose(f);
}

static void shortcut(const char *name, const char *id) {
    char rel[PATH_MAX], run[256];
    snprintf(rel, sizeof(rel), "Applications/%s.app/Contents/MacOS/run.sh", name);
    // Byte for byte what Steam writes, trailing blank line included.
    snprintf(run, sizeof(run), "%s\nopen steam://run/%s\n\n", RUN_SH_HEAD, id);
    write_at(rel, run);
}

static void launched(const char *id) {
    char rel[PATH_MAX];
    snprintf(rel, sizeof(rel), "Library/Application Support/notproton/launchers/%s", id);
    write_at(rel, NULL);
}

static void library(const char *apps) {
    char vdf[2048];
    snprintf(vdf, sizeof(vdf),
             "\"libraryfolders\"\n{\n\t\"0\"\n\t{\n"
             "\t\t\"path\"\t\t\"%s/lib\"\n"
             "\t\t\"apps\"\n\t\t{\n%s\t\t}\n\t}\n}\n", home, apps);
    write_at("Library/Application Support/Steam/steamapps/libraryfolders.vdf", vdf);
}

static void drop_home(void) {
    char cmd[PATH_MAX + 16];
    snprintf(cmd, sizeof(cmd), "rm -rf '%s'", home);
    if (home[0]) system(cmd);
}

static void fresh_home(void) {
    drop_home();
    snprintf(home, sizeof(home), "/tmp/np-shortcutcheck-XXXXXX");
    if (!mkdtemp(home)) {
        perror("mkdtemp");
        exit(1);
    }
    setenv("HOME", home, 1);
    write_at(".Trash", NULL);
}

static void expect(const char *rel, int present, const char *what) {
    char path[PATH_MAX];
    struct stat st;
    snprintf(path, sizeof(path), "%s/%s", home, rel);
    if ((stat(path, &st) == 0) != present) {
        printf("FAIL %s: %s should %s\n", what, rel, present ? "exist" : "be gone");
        failures++;
    }
}

int main(void) {
    fresh_home();
    library("\t\t\t\"200\"\t\t\"1234\"\n");
    write_at("lib/steamapps/appmanifest_300.acf", "\"AppState\"\n{\n}\n");
    shortcut("Gone", "100");               launched("100");
    shortcut("Listed", "200");             launched("200");
    shortcut("Manifest", "300");           launched("300");
    shortcut("Mac Game", "400");
    shortcut("Edited", "500");             launched("500");
    write_at("Applications/Edited.app/Contents/MacOS/run.sh",
             "#!/bin/bash\n# autogenerated file - do not edit\n\nopen steam://run/500\necho hi\n");
    write_at(".Trash/Gone.app", NULL);
    np_shortcuts_sweep();
    expect("Applications/Gone.app", 0, "uninstalled game");
    expect(".Trash/Gone.app", 1, "the earlier trashed copy");
    expect("Applications/Listed.app", 1, "game in the library's apps");
    expect("Applications/Manifest.app", 1, "game with an appmanifest");
    expect("Applications/Mac Game.app", 1, "game NotProton never launched");
    expect("Applications/Edited.app", 1, "shortcut Steam did not write");

    char trash_path[PATH_MAX];
    snprintf(trash_path, sizeof(trash_path), "%s/.Trash", home);
    DIR *trash = opendir(trash_path);
    int renamed = 0;
    struct dirent *e;
    while (trash && (e = readdir(trash)))
        if (strncmp(e->d_name, "Gone ", 5) == 0) renamed = 1;
    if (trash) closedir(trash);
    if (!renamed) {
        printf("FAIL name clash: the swept shortcut should land as \"Gone <time>.app\"\n");
        failures++;
    }

    fresh_home();
    shortcut("Gone", "100");
    launched("100");
    np_shortcuts_sweep();
    expect("Applications/Gone.app", 1, "no libraryfolders.vdf");

    drop_home();

    if (failures) {
        printf("==> shortcutcheck: %d check(s) failed\n", failures);
        return 1;
    }
    printf("==> shortcutcheck: uninstalled games lose their shortcut, everything else is kept\n");
    return 0;
}
