#include "shortcuts.h"
#include "../util/log.h"
#include "../util/file.h"

#include <dirent.h>
#include <limits.h>
#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include <sys/stat.h>
#include <time.h>

// Steam writes this run.sh into every game shortcut it puts in ~/Applications.
static const char RUN_SH_HEAD[] = "#!/bin/bash\n# autogenerated file - do not edit\n";
static const char RUN_SH_OPEN[] = "\nopen steam://run/";

static int all_digits(const char *s) {
    if (!*s) return 0;
    for (; *s; s++)
        if (*s < '0' || *s > '9') return 0;
    return 1;
}

// Reads the next quoted VDF token on this line into out. Returns the position after it.
static const char *vdf_token(const char *p, char *out, size_t size) {
    while (*p && *p != '\n' && *p != '"') p++;
    if (*p != '"') return NULL;
    p++;
    size_t n = 0;
    while (*p && *p != '\n' && *p != '"') {
        if (*p == '\\' && p[1] && p[1] != '\n') p++;
        if (n + 1 < size) out[n++] = *p;
        p++;
    }
    out[n] = '\0';
    return *p == '"' ? p + 1 : NULL;
}

// An app counts as installed while any library's "apps" block lists it or any
// library has its appmanifest. The "apps" block keeps games on unplugged drives.
static int app_installed(const char *vdf, const char *id) {
    char key[PATH_MAX], value[PATH_MAX], manifest[PATH_MAX];
    struct stat st;

    const char *line = vdf;
    while (line) {
        const char *p = vdf_token(line, key, sizeof(key));
        if (p && vdf_token(p, value, sizeof(value))) {
            if (strcmp(key, id) == 0 && all_digits(value)) return 1;
            if (strcmp(key, "path") == 0) {
                snprintf(manifest, sizeof(manifest), "%s/steamapps/appmanifest_%s.acf", value, id);
                if (stat(manifest, &st) == 0) return 1;
            }
        }
        line = strchr(line, '\n');
        if (line) line++;
    }
    return 0;
}

// Returns the app id from a Steam-generated shortcut, or 0 for anything else.
static int shortcut_app_id(const char *app, char *id, size_t size) {
    char path[PATH_MAX];
    snprintf(path, sizeof(path), "%s/Contents/MacOS/run.sh", app);

    size_t len = 0;
    char *run = (char *)np_read_whole_file(path, &len);
    if (!run) return 0;

    int ok = 0;
    if (len < 4096 && strncmp(run, RUN_SH_HEAD, sizeof(RUN_SH_HEAD) - 1) == 0) {
        char *buf = realloc(run, len + 1);
        if (buf) {
            run = buf;
            run[len] = '\0';
            const char *open = strstr(run, RUN_SH_OPEN);
            if (open) {
                const char *digits = open + sizeof(RUN_SH_OPEN) - 1;
                size_t n = strspn(digits, "0123456789");
                const char *rest = digits + n;
                if (n > 0 && n < size && rest[strspn(rest, "\n")] == '\0') {
                    memcpy(id, digits, n);
                    id[n] = '\0';
                    ok = 1;
                }
            }
        }
    }
    free(run);
    return ok;
}

static void move_to_trash(const char *home, const char *app, const char *name) {
    char dest[PATH_MAX];
    struct stat st;

    snprintf(dest, sizeof(dest), "%s/.Trash/%s", home, name);
    if (lstat(dest, &st) == 0) {
        size_t stem = strlen(name) - 4;  // drop ".app"
        snprintf(dest, sizeof(dest), "%s/.Trash/%.*s %ld.app", home, (int)stem, name, (long)time(NULL));
    }
    if (rename(app, dest) == 0)
        NP_LOG("shortcuts: moved %s to the Trash, its game is uninstalled", app);
    else
        NP_WARN("shortcuts: could not move %s to the Trash", app);
}

// Steam leaves a game's ~/Applications shortcut behind when the game is uninstalled.
// Trash the ones for games NotProton has launched.
void np_shortcuts_sweep(void) {
    const char *home = np_home_dir();
    if (!home) return;

    char path[PATH_MAX];
    snprintf(path, sizeof(path), "%s/Library/Application Support/Steam/steamapps/libraryfolders.vdf", home);
    size_t len = 0;
    char *vdf = (char *)np_read_whole_file(path, &len);
    if (!vdf) return;
    char *buf = realloc(vdf, len + 1);
    if (!buf) {
        free(vdf);
        return;
    }
    vdf = buf;
    vdf[len] = '\0';

    snprintf(path, sizeof(path), "%s/Applications", home);
    DIR *dir = opendir(path);
    if (!dir) {
        free(vdf);
        return;
    }

    struct dirent *entry;
    while ((entry = readdir(dir))) {
        size_t n = strlen(entry->d_name);
        if (n <= 4 || strcmp(entry->d_name + n - 4, ".app") != 0) continue;

        char app[PATH_MAX], id[16], launcher[PATH_MAX];
        struct stat st;
        snprintf(app, sizeof(app), "%s/%s", path, entry->d_name);
        if (!shortcut_app_id(app, id, sizeof(id))) continue;

        np_support_path(launcher, sizeof(launcher), home, "launchers");
        strlcat(launcher, "/", sizeof(launcher));
        strlcat(launcher, id, sizeof(launcher));
        if (stat(launcher, &st) != 0 || !S_ISDIR(st.st_mode)) continue;
        if (app_installed(vdf, id)) continue;

        move_to_trash(home, app, entry->d_name);
    }
    closedir(dir);
    free(vdf);
}
